<?php

	$id = '';
	if (!empty($this->zoneconfig['conf']['id']) && !$this->prefixId)
		$id = 'id="' . $this->zoneconfig['conf']['id'] . '"';
	else
		$id = 'id="' . $this->idPage . '_' . $this->zoneconfig['conf']['id'] . '"';
	
        $data_melisKey = $this->melisKey;
	
?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> role="tabpanel" class="tab-pane">
	<div class="row row-app">
        <div class="col-md-4">
            <?php echo $this->melismessenger_tool_inbox;?>
            <!-- // END col-separator -->
        </div>
        <!-- // END col -->
        <div class="col-md-8">
            <?php echo $this->melismessenger_tool_content;?>
        </div>
    </div>
</div>

