<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="'. $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id.' '.$data_melisKey; ?>>
    <!-- Chat -->
    <div class="widget widget-inverse widget-chat" id="convo-content">
        <div class="widget-head">
        	<div class="btn-group pull-right btn-group-xs">
    			<a class="btn btn-default refresh-chat" data-toggle="tab"><i class="fa fa-refresh"></i></a>
    		</div>
            <h4 class="heading"><i class="icon-comment-fill-1"></i> Chat</h4>
        </div>
        <div class="widget-body padding-none border-bottom">
        	<div id="convo-header"></div>
            <!-- Slim Scroll -->
            <div id="chat-container" class="slim-scroll" data-scroll-height="235px" data-scroll-size="0">
                <!-- Media item -->
                <!--Display all the conversation here from javascript-->
                <!-- // Media item END -->
            </div>
            <!-- // Slim Scroll END -->
        </div>
        <div class="chat-controls bg-default innerAll half">
            <div id="chat-form">
				<?php
					$form = $this->melismessenger_form;
					$form->prepare();
					echo $this->form()->openTag($form); 
					echo $this->melisFieldCollection($form);
					echo $this->form()->closeTag(); 
				?>
            </div>
        </div>
    </div> <!-- // Chat END -->
</div>